// <auto-generated />
using System;
using ConnectA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ConnectA.Infrastructure.Migrations
{
    [DbContext(typeof(OracleContext))]
    partial class OracleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConnectA.Domain.Entities.LearningTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("SeniorId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("senior_id");

                    b.HasKey("Id");

                    b.HasIndex("SeniorId");

                    b.ToTable("learning_tracks", (string)null);
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.LearningTrackUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("LearningTrackId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("learning_track_id");

                    b.Property<double?>("Score")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("score");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LearningTrackId");

                    b.HasIndex("UserId");

                    b.ToTable("learning_track_users", (string)null);
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.MentorshipChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("MentorshipMatchId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("mentorship_match_id");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("MentorshipMatchId");

                    b.ToTable("mentorship_challenges", (string)null);
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.MentorshipEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Evaluator")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("MentorshipMatchId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Rating")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("MentorshipMatchId");

                    b.ToTable("mentorship_evaluations", (string)null);
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.MentorshipMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<double>("CompatibilityScore")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<Guid>("JuniorId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("junior_id");

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("SeniorId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("senior_id");

                    b.HasKey("Id");

                    b.HasIndex("JuniorId");

                    b.HasIndex("SeniorId");

                    b.ToTable("mentorship_matches", (string)null);
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("biography");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("experience");

                    b.Property<string>("Lenguages")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("lenguages");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("location");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("objectives");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("skills");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.TrackStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("activity_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("description");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("estimated_duration");

                    b.Property<Guid>("LearningTrackId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("learning_track_id");

                    b.Property<int>("Order")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("order");

                    b.Property<string>("ResourceLink")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("resource_link");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("LearningTrackId");

                    b.ToTable("track_stages", (string)null);
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.LearningTrack", b =>
                {
                    b.HasOne("ConnectA.Domain.Entities.User", "Senior")
                        .WithMany("LearningTracksAsSenior")
                        .HasForeignKey("SeniorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Senior");
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.LearningTrackUser", b =>
                {
                    b.HasOne("ConnectA.Domain.Entities.LearningTrack", "LearningTrack")
                        .WithMany("Users")
                        .HasForeignKey("LearningTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConnectA.Domain.Entities.User", "User")
                        .WithMany("LearningTracksFolows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningTrack");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.MentorshipChallenge", b =>
                {
                    b.HasOne("ConnectA.Domain.Entities.MentorshipMatch", "MentorshipMatch")
                        .WithMany("Challenges")
                        .HasForeignKey("MentorshipMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MentorshipMatch");
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.MentorshipEvaluation", b =>
                {
                    b.HasOne("ConnectA.Domain.Entities.MentorshipMatch", "MentorshipMatch")
                        .WithMany("Evaluations")
                        .HasForeignKey("MentorshipMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MentorshipMatch");
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.MentorshipMatch", b =>
                {
                    b.HasOne("ConnectA.Domain.Entities.User", "Junior")
                        .WithMany("MatchesAsJunior")
                        .HasForeignKey("JuniorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConnectA.Domain.Entities.User", "Senior")
                        .WithMany("MatchesAsSenior")
                        .HasForeignKey("SeniorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Junior");

                    b.Navigation("Senior");
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.Profile", b =>
                {
                    b.HasOne("ConnectA.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("ConnectA.Domain.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.TrackStage", b =>
                {
                    b.HasOne("ConnectA.Domain.Entities.LearningTrack", "LearningTrack")
                        .WithMany("Stages")
                        .HasForeignKey("LearningTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningTrack");
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.LearningTrack", b =>
                {
                    b.Navigation("Stages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.MentorshipMatch", b =>
                {
                    b.Navigation("Challenges");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("ConnectA.Domain.Entities.User", b =>
                {
                    b.Navigation("LearningTracksAsSenior");

                    b.Navigation("LearningTracksFolows");

                    b.Navigation("MatchesAsJunior");

                    b.Navigation("MatchesAsSenior");

                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
